name:
  build
on:
  push
jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, '>>>')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alaviss/setup-nim@master
        with:
          path: '../nim'
          version: 'version-1-4'
      - run: |
          wget "https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v${TS_VERSION}.tar.gz" && \
          tar -xvf "v${TS_VERSION}.tar.gz" && \
          cd "tree-sitter-${TS_VERSION}" && \
          sudo make install PREFIX=/usr
        env:
          TS_VERSION: "0.20.0"

      - run: "nimble -y test && nimble install -y"
      - run: "nimble docgen"
      - uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
